[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "python3Packages.pip", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
    "npm ci --only=production --ignore-scripts",
    "pip3 install --upgrade yt-dlp"
]

[phases.build]
cmds = ["echo 'Build phase - no build needed'"]

[start]
cmd = "node start.js"